# Generated by Django 3.1.5 on 2021-02-01 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210130_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privateserver',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
